### ISSUE TITLE
This link is no longer active - Slack

### ISSUE THREAD

**Issue by stefanos82** [ClassicPress/site-www#22]
The link https://www.classicpress.net/join-slack/ from upper left corner of main page does not work.

![image](https://user-images.githubusercontent.com/1777466/96194966-2d808900-0f54-11eb-91e4-294153a4b6dd.png)

I have an account for WooCommerce and cannot use it to sign in on classicpress workspace.

Can anyone advice me what to do?

**Comment by nylen** [comment]
Thanks for reporting this.

> Can anyone advice me what to do?

Try https://www.classicpress.net/join-slack/ again - I've just updated the redirect to a fresh invite link.

**Comment by stefanos82** [comment]
I have an account on slack that I use for woocommerce and upon joining on classicpress, I get the following email:

```log
You recently tried to create an account for foo@example.com on ClassicPress,
but it looks like an account for that email address already exists and is deactivated.
We’re sorry about that!

If you think this was a mistake, please contact a Workspace Administrator 
to reactivate the account.
```

**Comment by nylen** [comment]
You used to have an account on that email address, and you deactivated it. I have reactivated the account.
